//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sudoku.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sudoku.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_Bold {
            get {
                object obj = ResourceManager.GetObject("Eurostile Bold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_Bold_Extended {
            get {
                object obj = ResourceManager.GetObject("Eurostile Bold Extended", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_Bold_Oblique {
            get {
                object obj = ResourceManager.GetObject("Eurostile Bold Oblique", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_Candy_LT_W04_Regular {
            get {
                object obj = ResourceManager.GetObject("Eurostile Candy LT W04 Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_Candy_LT_W04_Semibold {
            get {
                object obj = ResourceManager.GetObject("Eurostile Candy LT W04 Semibold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_Condensed {
            get {
                object obj = ResourceManager.GetObject("Eurostile Condensed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_Condensed_Bold {
            get {
                object obj = ResourceManager.GetObject("Eurostile Condensed Bold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_Demi_Oblique {
            get {
                object obj = ResourceManager.GetObject("Eurostile Demi Oblique", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_Italic {
            get {
                object obj = ResourceManager.GetObject("Eurostile Italic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_LT_Bold {
            get {
                object obj = ResourceManager.GetObject("Eurostile LT Bold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_LT_Bold_Oblique {
            get {
                object obj = ResourceManager.GetObject("Eurostile LT Bold Oblique", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_LT_Condensed {
            get {
                object obj = ResourceManager.GetObject("Eurostile LT Condensed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_LT_Demi {
            get {
                object obj = ResourceManager.GetObject("Eurostile LT Demi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_LT_Demi_Oblique {
            get {
                object obj = ResourceManager.GetObject("Eurostile LT Demi Oblique", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_LT_Oblique {
            get {
                object obj = ResourceManager.GetObject("Eurostile LT Oblique", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_LT_Std_Bold {
            get {
                object obj = ResourceManager.GetObject("Eurostile LT Std Bold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_LT_Std_Bold_Condensed {
            get {
                object obj = ResourceManager.GetObject("Eurostile LT Std Bold Condensed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_LT_Std_Bold_Extended_2 {
            get {
                object obj = ResourceManager.GetObject("Eurostile LT Std Bold Extended 2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_LT_Std_Bold_Oblique {
            get {
                object obj = ResourceManager.GetObject("Eurostile LT Std Bold Oblique", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_LT_Std_Condensed {
            get {
                object obj = ResourceManager.GetObject("Eurostile LT Std Condensed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_LT_Std_Demi {
            get {
                object obj = ResourceManager.GetObject("Eurostile LT Std Demi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_LT_Std_Demi_Oblique {
            get {
                object obj = ResourceManager.GetObject("Eurostile LT Std Demi Oblique", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_LT_Std_Extended_2 {
            get {
                object obj = ResourceManager.GetObject("Eurostile LT Std Extended 2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_LT_Std_Medium {
            get {
                object obj = ResourceManager.GetObject("Eurostile LT Std Medium", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_LT_Std_Oblique {
            get {
                object obj = ResourceManager.GetObject("Eurostile LT Std Oblique", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_LT_Std_Roman {
            get {
                object obj = ResourceManager.GetObject("Eurostile LT Std Roman", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_LT_W03_Bold_Condensed {
            get {
                object obj = ResourceManager.GetObject("Eurostile LT W03 Bold Condensed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_LT_W03_Bold_Oblique {
            get {
                object obj = ResourceManager.GetObject("Eurostile LT W03 Bold Oblique", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_LT_W03_Condensed {
            get {
                object obj = ResourceManager.GetObject("Eurostile LT W03 Condensed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_LT_W03_Demi_Oblique {
            get {
                object obj = ResourceManager.GetObject("Eurostile LT W03 Demi Oblique", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_LT_W03_Extended_2 {
            get {
                object obj = ResourceManager.GetObject("Eurostile LT W03 Extended 2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_LT_W03_Oblique {
            get {
                object obj = ResourceManager.GetObject("Eurostile LT W03 Oblique", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_LT_W04_Bold_Condensed {
            get {
                object obj = ResourceManager.GetObject("Eurostile LT W04 Bold Condensed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_LT_W04_Bold_Ext_2 {
            get {
                object obj = ResourceManager.GetObject("Eurostile LT W04 Bold Ext 2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_LT_W04_Bold_Oblique {
            get {
                object obj = ResourceManager.GetObject("Eurostile LT W04 Bold Oblique", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_LT_W04_Condensed {
            get {
                object obj = ResourceManager.GetObject("Eurostile LT W04 Condensed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_LT_W04_Demi_Oblique {
            get {
                object obj = ResourceManager.GetObject("Eurostile LT W04 Demi Oblique", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_LT_W04_Oblique {
            get {
                object obj = ResourceManager.GetObject("Eurostile LT W04 Oblique", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_Next_LT_W04_Bold_Cond {
            get {
                object obj = ResourceManager.GetObject("Eurostile Next LT W04 Bold Cond", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_Next_LT_W04_Ult_Light {
            get {
                object obj = ResourceManager.GetObject("Eurostile Next LT W04 Ult Light", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_Next_LT_W04_Ult_Lt_Ex {
            get {
                object obj = ResourceManager.GetObject("Eurostile Next LT W04 Ult Lt Ex", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Eurostile_Oblique {
            get {
                object obj = ResourceManager.GetObject("Eurostile Oblique", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] EurostileEF_Black {
            get {
                object obj = ResourceManager.GetObject("EurostileEF-Black", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] EurostileEF_Regular {
            get {
                object obj = ResourceManager.GetObject("EurostileEF-Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] EurostileLTStd_BoldOblique {
            get {
                object obj = ResourceManager.GetObject("EurostileLTStd-BoldOblique", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
